// AI glossary — 50 entries. Each renders to /glossary/<slug>/ with
// DefinedTerm + DefinedTermSet JSON-LD. Definitional queries pull AI search
// citations heavily; this is one of the highest-ROI SEO surfaces.

export interface GlossaryEntry {
  slug: string;
  term: string;
  short: string;          // 1-line summary (used in cards + meta description)
  body: string;           // 100-200 word definition
  category: string;       // shown as eyebrow + filter
  alsoKnownAs?: string[]; // synonyms
  related: string[];      // other glossary slugs
  /** Internal pillar/blog links most relevant to this term. */
  pillarLinks?: { name: string; href: string }[];
}

const PILLAR_GENERAL = [
  { name: "AI Execution School", href: "/ai-execution-school/" },
  { name: "AI Generalist program", href: "/programs/ai-generalist/" },
];
const PILLAR_AUTOMATION = [
  { name: "AI Automation course", href: "/ai-automation-course/" },
  { name: "Best AI automation course in India", href: "/blog/best-ai-automation-course-in-india/" },
];
const PILLAR_BEGINNERS = [
  { name: "AI course for beginners", href: "/ai-course-for-beginners/" },
  { name: "How to learn AI without coding", href: "/blog/how-to-learn-ai-without-coding/" },
];

export const glossary: GlossaryEntry[] = [
  // ── Core LLM concepts ───────────────────────────────────────────────
  {
    slug: "llm",
    term: "LLM (Large Language Model)",
    short: "An AI model trained on huge amounts of text that can understand and generate human language.",
    body: "A Large Language Model (LLM) is an AI system trained on hundreds of billions of words from books, websites, and articles. Modern LLMs like Claude, GPT-4, and Gemini can write, summarise, translate, code, and reason across most knowledge domains. Practically, an LLM is what you talk to inside Claude, ChatGPT, or any AI chat tool. The 'large' part refers to the model size (parameters, often hundreds of billions) and the training data scale. For applied AI, you don't need to train an LLM — you call existing ones via APIs.",
    category: "Models",
    alsoKnownAs: ["Large Language Model", "Foundation Model", "Chat AI"],
    related: ["claude", "chatgpt", "gemini", "prompt-engineering", "tokens"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "claude",
    term: "Claude",
    short: "Anthropic's family of AI assistants — known for strong reasoning, long context, and code quality.",
    body: "Claude is the AI assistant built by Anthropic. As of 2026, Claude models lead in coding, structured reasoning, and following complex instructions. Claude is the default LLM ONROL teaches because of its strong performance on real-world tasks (vibe coding, agent workflows, document analysis) and 200k+ token context window. Available via the chat interface (claude.ai), API, and inside tools like Cursor and many no-code platforms.",
    category: "Tools",
    related: ["llm", "chatgpt", "gemini", "vibe-coding", "context-window"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "chatgpt",
    term: "ChatGPT",
    short: "OpenAI's flagship AI chat product, the most-used LLM globally.",
    body: "ChatGPT is OpenAI's consumer-facing LLM product, launched in 2022. As of 2026 it powers GPT-4 family models (GPT-4o, GPT-4.5, etc.) and remains the most-used AI chat tool worldwide. ChatGPT is excellent for general writing, brainstorming, and creative tasks. Available at chat.openai.com or via API. ONROL covers ChatGPT alongside Claude, Gemini, and Perplexity in its prompt-mastery module.",
    category: "Tools",
    related: ["llm", "claude", "gemini", "openai", "prompt-engineering"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "gemini",
    term: "Gemini",
    short: "Google's AI assistant family, deeply integrated with Google Workspace.",
    body: "Gemini is Google's AI model family (formerly Bard). Strongest use cases in 2026: Google Workspace integration (Docs, Sheets, Gmail), long-context document analysis, and multimodal reasoning. Gemini Advanced powers the consumer chat at gemini.google.com. The Gemini API is widely used by developers building production AI apps.",
    category: "Tools",
    related: ["llm", "claude", "chatgpt", "google-ai-studio"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "perplexity",
    term: "Perplexity",
    short: "An AI-powered search engine that cites its sources.",
    body: "Perplexity is an AI search engine that combines an LLM with web search. Unlike traditional ChatGPT/Claude which sometimes hallucinate facts, Perplexity grounds every answer in cited sources. Excellent for research, fact-finding, and current events. ONROL teaches Perplexity as the default research tool because it makes verification trivial.",
    category: "Tools",
    related: ["chatgpt", "claude", "ai-search", "rag"],
    pillarLinks: PILLAR_GENERAL,
  },
  {
    slug: "groq",
    term: "Groq",
    short: "A high-speed AI inference provider — 10x faster than typical APIs.",
    body: "Groq is an AI inference company that runs open-weight models (Llama, Mixtral, etc.) on custom LPU hardware, achieving 5-10x the response speed of typical cloud APIs. Use case: real-time AI features where latency matters (chat assistants, voice interfaces). ONROL's tools.onrol.in suite uses Groq via withRotation() in production — gives sub-second LLM responses for end users.",
    category: "Tools",
    related: ["llm", "inference", "api"],
  },
  {
    slug: "openai",
    term: "OpenAI",
    short: "The company behind ChatGPT and GPT models.",
    body: "OpenAI is the AI lab that created ChatGPT, the GPT model family, DALL-E (image generation), and Whisper (speech recognition). Founded in 2015, OpenAI's products in 2026 dominate consumer AI usage. Their developer platform (platform.openai.com) provides APIs for every product.",
    category: "Companies",
    related: ["chatgpt", "anthropic", "google-deepmind"],
  },
  {
    slug: "anthropic",
    term: "Anthropic",
    short: "The AI safety company that builds Claude.",
    body: "Anthropic is an AI safety company founded by former OpenAI researchers. They build the Claude family of LLMs and pioneered Constitutional AI, a technique that uses AI feedback to align model behaviour. Claude.ai is their consumer product; the Anthropic API powers thousands of production apps.",
    category: "Companies",
    related: ["claude", "openai", "google-deepmind"],
  },
  {
    slug: "google-deepmind",
    term: "Google DeepMind",
    short: "Google's AI research arm — builds Gemini, AlphaFold, and more.",
    body: "Google DeepMind is the merged AI research division of Google (Google Brain + DeepMind, combined in 2023). Builds the Gemini model family, AlphaFold (protein structure prediction), and many of Google's underlying AI systems.",
    category: "Companies",
    related: ["gemini", "openai", "anthropic"],
  },

  // ── Prompting & techniques ────────────────────────────────────────
  {
    slug: "prompt-engineering",
    term: "Prompt Engineering",
    short: "The craft of designing inputs to LLMs to get reliable, high-quality outputs.",
    body: "Prompt engineering is the practice of writing structured AI inputs — including role assignments, output formats, examples, and constraints — to consistently get the desired behaviour from an LLM. Good prompt engineering is the difference between a 60%-quality output and a 95%-quality one. ONROL spends Day 1 of the Generalist track entirely on prompt patterns: structured prompts, chain-of-thought, few-shot examples, output formatting, and hallucination reduction.",
    category: "Techniques",
    alsoKnownAs: ["Prompt Design", "Prompting"],
    related: ["llm", "chain-of-thought", "few-shot", "system-prompt", "tokens"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "chain-of-thought",
    term: "Chain-of-Thought (CoT)",
    short: "A prompting technique where you ask the AI to think step-by-step before answering.",
    body: "Chain-of-Thought (CoT) is a prompting technique where you instruct the LLM to reason through a problem step-by-step before giving a final answer. CoT dramatically improves accuracy on multi-step reasoning tasks (math, logic, complex analysis). Trigger phrases: 'Let's think step by step,' 'Show your reasoning,' 'Walk through this carefully.' Modern models (Claude 3.5+, GPT-4o, o1) often do this internally.",
    category: "Techniques",
    related: ["prompt-engineering", "few-shot", "tree-of-thought"],
  },
  {
    slug: "few-shot",
    term: "Few-Shot Prompting",
    short: "Showing the AI 2-5 examples of the desired output before asking for a new one.",
    body: "Few-shot prompting means including 2-5 worked examples in your prompt before asking the LLM to do a new task. The model picks up the pattern from the examples and applies it. Especially useful for output-formatting tasks where you want consistent structure (JSON schemas, specific tones, custom layouts).",
    category: "Techniques",
    related: ["prompt-engineering", "chain-of-thought", "zero-shot"],
  },
  {
    slug: "zero-shot",
    term: "Zero-Shot Prompting",
    short: "Asking the AI to do a task with no examples, just instructions.",
    body: "Zero-shot prompting means giving an LLM a task description without any examples. Modern LLMs are remarkably capable at zero-shot, especially with clear instructions. Use it as the default; only switch to few-shot when zero-shot is unreliable for your specific output format.",
    category: "Techniques",
    related: ["few-shot", "prompt-engineering"],
  },
  {
    slug: "system-prompt",
    term: "System Prompt",
    short: "The hidden instruction that shapes an AI's persona, rules, and behaviour.",
    body: "A system prompt is the instruction set that runs before any user message — it defines the AI's persona, rules, output format, and constraints. Most production AI apps live or die on system prompt quality. ONROL teaches system-prompt design as a separate skill from regular prompting because the failure modes are different (drift, instruction-following, role-leakage).",
    category: "Techniques",
    related: ["prompt-engineering", "ai-agent", "rag"],
  },
  {
    slug: "tree-of-thought",
    term: "Tree-of-Thought (ToT)",
    short: "An advanced reasoning technique where the AI explores multiple reasoning paths.",
    body: "Tree-of-Thought (ToT) extends chain-of-thought by having the LLM branch into multiple reasoning paths, evaluate each, then converge on the best one. Useful for hard problems where the first reasoning path might be wrong. Implemented via prompting or via agent frameworks that orchestrate multiple LLM calls.",
    category: "Techniques",
    related: ["chain-of-thought", "ai-agent"],
  },

  // ── RAG, fine-tuning, vectors ──────────────────────────────────────
  {
    slug: "rag",
    term: "RAG (Retrieval-Augmented Generation)",
    short: "Giving an AI access to your private documents so it can answer questions about them.",
    body: "RAG (Retrieval-Augmented Generation) is the technique of giving an LLM access to specific documents at query time. The flow: documents are embedded into vectors, stored in a vector database, retrieved on each query based on relevance, and stuffed into the prompt before the LLM responds. RAG turns an LLM into a private knowledge assistant. ONROL teaches RAG on Day 2 of the Generalist track using Supabase pgvector + Claude.",
    category: "Techniques",
    alsoKnownAs: ["Retrieval Augmented Generation", "Document Q&A"],
    related: ["embedding", "vector-database", "fine-tuning", "context-window"],
    pillarLinks: PILLAR_GENERAL,
  },
  {
    slug: "fine-tuning",
    term: "Fine-Tuning",
    short: "Adjusting a pre-trained AI model on your specific data to change its behaviour.",
    body: "Fine-tuning is the process of further training a pre-trained LLM on your custom dataset (examples of inputs + desired outputs) to teach it your specific style, voice, or task patterns. Use cases: brand-voice locking, specialised classification, domain-specific tone. In 2026, fine-tuning is increasingly replaced by RAG + good prompting for most tasks because it's cheaper and faster to iterate.",
    category: "Techniques",
    related: ["rag", "lora", "embedding", "training-data"],
  },
  {
    slug: "lora",
    term: "LoRA (Low-Rank Adaptation)",
    short: "An efficient way to fine-tune large models by training only a small set of new parameters.",
    body: "LoRA (Low-Rank Adaptation) is a fine-tuning technique that adds small trainable layers to a frozen base model. Result: 100x cheaper than full fine-tuning, with comparable quality for most tasks. The standard technique for fine-tuning open-source models like Llama. ONROL covers LoRA in the Architect track.",
    category: "Techniques",
    related: ["fine-tuning", "rag"],
  },
  {
    slug: "embedding",
    term: "Embedding",
    short: "A numeric representation of text (or image) that captures its meaning.",
    body: "An embedding is a vector of numbers (typically 384-1536 dimensions) that represents the semantic meaning of a piece of text, image, or audio. Similar meanings produce similar vectors. Embeddings power RAG, semantic search, recommendation systems, and clustering. Generated by embedding models like OpenAI's text-embedding-3, Cohere Embed, or open-source alternatives.",
    category: "Techniques",
    related: ["rag", "vector-database", "semantic-search"],
  },
  {
    slug: "vector-database",
    term: "Vector Database",
    short: "A database optimised for storing and searching embeddings by similarity.",
    body: "A vector database stores embeddings and lets you query by similarity — 'find documents most similar to this query.' Core infrastructure for RAG. Common options: Pinecone (managed, fast), Supabase pgvector (PostgreSQL extension, what ONROL teaches), Weaviate (open-source, feature-rich), Chroma (lightweight, dev-friendly).",
    category: "Tools",
    related: ["embedding", "rag", "semantic-search"],
  },
  {
    slug: "semantic-search",
    term: "Semantic Search",
    short: "Search that understands meaning, not just keyword matches.",
    body: "Semantic search uses embeddings to match queries to documents by meaning rather than exact keyword matches. A query for 'how to grow my IG account' returns documents about 'Instagram audience building' even if those exact words don't appear. Powers RAG and modern search interfaces.",
    category: "Techniques",
    related: ["embedding", "vector-database", "rag"],
  },
  {
    slug: "training-data",
    term: "Training Data",
    short: "The text, images, or examples used to teach an AI model what to do.",
    body: "Training data is the dataset an AI model learns from. For LLMs, this is typically billions of pages of internet text plus curated high-quality examples. For fine-tuning, you supply specific input/output examples. Quality of training data is the single biggest determinant of model quality.",
    category: "Techniques",
    related: ["fine-tuning", "lora", "llm"],
  },

  // ── Agents & orchestration ─────────────────────────────────────────
  {
    slug: "ai-agent",
    term: "AI Agent",
    short: "An AI system that decides its own next action and takes multi-step actions autonomously.",
    body: "An AI agent is an LLM-driven system that can plan, decide, and execute multi-step actions without human intervention at each step. Examples: an agent that reads your email, drafts replies, and schedules follow-ups; an agent that researches a topic by browsing the web and writing a report. Agents are the 'AI does the whole job, not just one step' frontier. ONROL's Architect track covers agent design + safety patterns.",
    category: "Concepts",
    alsoKnownAs: ["Autonomous Agent", "AI Worker"],
    related: ["tool-use", "ai-orchestration", "rag", "system-prompt"],
    pillarLinks: PILLAR_AUTOMATION,
  },
  {
    slug: "ai-orchestration",
    term: "AI Orchestration",
    short: "Coordinating multiple AI calls, tools, and decisions into a single workflow.",
    body: "AI orchestration is the practice of chaining multiple LLM calls, tool invocations, and decision points into a single end-to-end workflow. Examples: a customer-support flow that classifies → retrieves → answers → escalates. Tools: LangChain, LangGraph, Vercel AI SDK, n8n, custom code. ONROL's AI Architect track is named for this skill.",
    category: "Concepts",
    related: ["ai-agent", "tool-use", "automation", "n8n"],
    pillarLinks: PILLAR_AUTOMATION,
  },
  {
    slug: "tool-use",
    term: "Tool Use",
    short: "An AI's ability to call external tools (APIs, code, search) instead of just generating text.",
    body: "Tool use is when an LLM decides to invoke an external tool — call an API, run code, search the web, query a database — instead of just generating text. Modern models (Claude with computer use, GPT-4 with function calling, Gemini) all support tool use. This is the foundation of AI agents.",
    category: "Concepts",
    alsoKnownAs: ["Function Calling", "Tool Calling"],
    related: ["ai-agent", "ai-orchestration", "mcp"],
  },
  {
    slug: "mcp",
    term: "MCP (Model Context Protocol)",
    short: "Anthropic's open standard for connecting AI assistants to external tools and data.",
    body: "MCP (Model Context Protocol) is an open standard introduced by Anthropic in 2024 for connecting LLMs to tools, files, and data sources. Think 'USB for AI tools.' MCP servers expose capabilities (read files, run queries, call APIs) and any MCP-aware LLM client can use them. Becoming the default integration layer for production AI in 2026.",
    category: "Concepts",
    related: ["tool-use", "ai-agent", "claude"],
  },
  {
    slug: "automation",
    term: "AI Automation",
    short: "Wiring AI into multi-step workflows so they run without human intervention.",
    body: "AI automation combines workflow automation tools (n8n, Zapier, Make) with LLM API calls so multi-step processes run autonomously. Common examples: lead qualification, content publishing, support triage, reporting. The highest-margin freelance service category in 2026.",
    category: "Concepts",
    related: ["ai-orchestration", "n8n", "zapier", "ai-agent"],
    pillarLinks: PILLAR_AUTOMATION,
  },
  {
    slug: "n8n",
    term: "n8n",
    short: "Open-source workflow automation platform with deep AI-node support.",
    body: "n8n is an open-source workflow automation tool — visual builder, self-hostable, free for personal use. Compared to Zapier: more powerful, more flexible, deeper AI integrations, no per-task pricing. The default automation tool ONROL teaches because it scales without per-user fees.",
    category: "Tools",
    related: ["zapier", "make-com", "automation", "ai-orchestration"],
    pillarLinks: PILLAR_AUTOMATION,
  },
  {
    slug: "zapier",
    term: "Zapier",
    short: "The most popular cloud workflow automation platform — easy UI, paid tiers.",
    body: "Zapier is a cloud workflow automation platform with the friendliest UI and the largest app integration library (6000+ apps). Best for non-technical users and small teams. Pricing scales with task volume, which gets expensive at scale — that's where teams switch to n8n.",
    category: "Tools",
    related: ["n8n", "make-com", "automation"],
  },
  {
    slug: "make-com",
    term: "Make.com",
    short: "A visual workflow automation tool — middle ground between Zapier and n8n.",
    body: "Make.com (formerly Integromat) is a visual automation tool with more power than Zapier and easier setup than n8n. Pricing is operations-based (cheaper than Zapier at scale). Strong AI-integration nodes and a flexible visual canvas.",
    category: "Tools",
    related: ["zapier", "n8n", "automation"],
  },

  // ── Vibe coding & dev tools ───────────────────────────────────────
  {
    slug: "vibe-coding",
    term: "Vibe Coding",
    short: "Building software by describing what you want in English while AI writes the code.",
    body: "Vibe coding is the 2024+ practice of building deployable software primarily through natural-language descriptions while AI generates and edits the code. Tools: Cursor, Bolt.new, Lovable, v0, Replit Agent. The biggest workflow shift in software development since the IDE. Non-coders can now ship deployable web apps in hours. ONROL's Day 3 is entirely vibe coding.",
    category: "Concepts",
    related: ["cursor", "bolt-new", "lovable", "v0"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "cursor",
    term: "Cursor",
    short: "An AI-first code editor — VS Code fork with deep Claude/GPT integration.",
    body: "Cursor is a code editor built on VS Code, with AI deeply integrated for autocomplete, refactoring, multi-file edits, and conversational code generation. The standard editor for AI-augmented developers in 2026. Premium tier required for the best models (Claude 3.5+).",
    category: "Tools",
    related: ["vibe-coding", "github-copilot", "bolt-new"],
  },
  {
    slug: "bolt-new",
    term: "Bolt.new",
    short: "AI app builder — describe a website in English, get a deployed live URL.",
    body: "Bolt.new (StackBlitz) is the fastest path from 'idea' to 'live deployed website.' You describe what you want in plain English; Bolt generates the full project, runs it in-browser, and deploys to Netlify with one click. ONROL's recommended starting point for non-coders building their first website.",
    category: "Tools",
    related: ["vibe-coding", "lovable", "v0", "replit"],
  },
  {
    slug: "lovable",
    term: "Lovable",
    short: "AI app builder — opinionated full-stack apps with Supabase backend.",
    body: "Lovable is an AI app builder that produces opinionated full-stack apps with Supabase as the backend, Tailwind for styling, and Vite for the frontend. Slightly slower than Bolt.new but produces more production-ready output. Strong choice for shipping a real SaaS MVP.",
    category: "Tools",
    related: ["vibe-coding", "bolt-new", "v0", "supabase"],
  },
  {
    slug: "v0",
    term: "v0 by Vercel",
    short: "AI UI generator — describe a component, get React + Tailwind code.",
    body: "v0 is Vercel's AI UI generator. Describe a component or page in English, get production-quality React + Tailwind code with shadcn/ui components. Best-in-class for design-quality AI output. Pairs well with Cursor for the rest of the stack.",
    category: "Tools",
    related: ["vibe-coding", "bolt-new", "lovable"],
  },
  {
    slug: "replit",
    term: "Replit",
    short: "Browser-based dev environment with an AI agent that builds full apps.",
    body: "Replit is a browser-based development platform with Replit Agent, an AI that builds and deploys full-stack apps from natural-language descriptions. Strong free tier; ideal for students and beginners learning to code with AI assistance.",
    category: "Tools",
    related: ["vibe-coding", "bolt-new", "lovable"],
  },
  {
    slug: "github-copilot",
    term: "GitHub Copilot",
    short: "GitHub's AI pair-programmer — AI autocomplete inside any editor.",
    body: "GitHub Copilot is the original AI coding assistant, now powered by GPT-4 family models. Available as plugins for VS Code, JetBrains, Neovim, and more. Best for inline autocomplete in your existing editor. Paid subscription required for individuals; free for verified students and OSS maintainers.",
    category: "Tools",
    related: ["cursor", "vibe-coding"],
  },

  // ── Infrastructure ────────────────────────────────────────────────
  {
    slug: "api",
    term: "API",
    short: "An interface for programs to call AI models or services programmatically.",
    body: "An API (Application Programming Interface) is the way one program talks to another. AI APIs (Claude API, OpenAI API, Gemini API) let you embed LLM capabilities into your own apps and workflows. Authentication is via API keys; pricing is usually per-token. ONROL teaches API basics in the Architect track.",
    category: "Infrastructure",
    related: ["llm", "tool-use", "webhook"],
  },
  {
    slug: "webhook",
    term: "Webhook",
    short: "A way for one app to notify another in real-time when an event happens.",
    body: "A webhook is an HTTP callback — when something happens in App A (a form submit, a payment, a new lead), App A sends a POST request to a URL in App B. Foundation of modern automation. n8n, Zapier, and Make all use webhooks heavily.",
    category: "Infrastructure",
    related: ["api", "n8n", "zapier", "automation"],
  },
  {
    slug: "supabase",
    term: "Supabase",
    short: "Open-source Firebase alternative — Postgres, Auth, Storage, Vector search in one.",
    body: "Supabase is the most popular open-source backend platform in 2026. PostgreSQL database, built-in auth, file storage, vector search (pgvector), real-time subscriptions — all under one API. ONROL's tools.onrol.in suite runs on Supabase.",
    category: "Tools",
    related: ["vector-database", "rag", "lovable"],
  },
  {
    slug: "vercel",
    term: "Vercel",
    short: "The hosting platform for modern web apps — deploys in seconds.",
    body: "Vercel is the standard hosting platform for modern web applications (Next.js, React, Vue, etc.). Free tier covers most personal and small projects. v0, the AI UI generator, is also a Vercel product. Most ONROL students deploy their Day-3 vibe-coded site to Vercel.",
    category: "Infrastructure",
    related: ["bolt-new", "v0", "lovable"],
  },
  {
    slug: "cloudflare",
    term: "Cloudflare",
    short: "Edge platform with AI Workers — runs ML models close to your users globally.",
    body: "Cloudflare runs a global edge network and provides AI services (Workers AI) that run inference close to your users with sub-100ms latency. Includes Workers AI for LLMs, image generation (Flux), and Whisper for speech. Free tier is generous. ONROL's tools.onrol.in image generation runs on Cloudflare Flux.",
    category: "Infrastructure",
    related: ["vercel", "supabase", "api"],
  },

  // ── Generic AI concepts ────────────────────────────────────────────
  {
    slug: "tokens",
    term: "Tokens",
    short: "The chunks of text LLMs process — roughly 0.75 words each.",
    body: "Tokens are the units LLMs read and write. A token is roughly a word or sub-word piece (e.g. 'unbelievable' might split into 'un', 'believ', 'able'). Pricing for AI APIs is per-token. Context windows are measured in tokens. Rough conversion: 1000 tokens ≈ 750 English words.",
    category: "Concepts",
    related: ["context-window", "llm", "api"],
  },
  {
    slug: "context-window",
    term: "Context Window",
    short: "The maximum text an LLM can read in one prompt.",
    body: "The context window is the maximum number of tokens an LLM can process at once — both the input prompt and the generated response. Modern frontier models have 200k-2M token context windows (Claude 3.7: 200k, Gemini 1.5 Pro: 2M). Bigger context = the model can read more of your documents at once without RAG.",
    category: "Concepts",
    related: ["tokens", "llm", "rag"],
  },
  {
    slug: "hallucination",
    term: "Hallucination",
    short: "When an AI confidently generates information that isn't true.",
    body: "Hallucination is when an LLM produces output that sounds confident but isn't factually accurate — invented citations, wrong numbers, fake quotes. Mitigation: ground responses in retrieved documents (RAG), require citations, set temperature lower, ask the model to express uncertainty when unsure. Still a top open problem in 2026.",
    category: "Concepts",
    related: ["rag", "prompt-engineering", "perplexity"],
  },
  {
    slug: "temperature",
    term: "Temperature",
    short: "An LLM setting that controls how 'creative' vs 'focused' outputs are.",
    body: "Temperature is a 0-2 setting that controls how diverse an LLM's outputs are. Temperature 0 = same input → same output (deterministic, focused). Temperature 1 = creative variation. Temperature >1 = random and chaotic. For most tasks, 0.3-0.7 is the sweet spot. For creative writing, 0.8-1.2.",
    category: "Concepts",
    related: ["prompt-engineering", "llm"],
  },
  {
    slug: "ai-search",
    term: "AI Search",
    short: "Search engines that answer questions in natural language with citations.",
    body: "AI Search refers to the new generation of search engines that combine LLMs with web indexing — Perplexity, ChatGPT Search, Google AI Overviews, Bing Copilot. Instead of returning a list of links, they synthesise an answer and cite sources. Increasingly the default way Indians search the web in 2026.",
    category: "Concepts",
    related: ["perplexity", "rag", "ai-overviews"],
  },
  {
    slug: "ai-overviews",
    term: "Google AI Overviews",
    short: "Google's AI-generated answers that appear at the top of search results.",
    body: "AI Overviews (formerly SGE — Search Generative Experience) is Google's AI-generated answer block that appears above the standard search results. Powered by Gemini, draws from indexed pages, cites sources. Major implication: SEO in 2026 means optimising for AI Overview citations, not just position-1 ranking.",
    category: "Concepts",
    related: ["ai-search", "perplexity", "seo"],
  },

  // ── Ecosystem terms ───────────────────────────────────────────────
  {
    slug: "applied-ai",
    term: "Applied AI",
    short: "The practical use of AI tools to ship products and outcomes.",
    body: "Applied AI is the use of existing AI models, tools, and APIs to ship real products, automations, and services. Distinct from research AI, which builds new models. Applied AI is what 95% of economic AI value comes from in 2026 — and what ONROL teaches end-to-end.",
    category: "Concepts",
    alsoKnownAs: ["Practical AI", "AI Execution"],
    related: ["academic-ai", "vibe-coding", "ai-agent", "ai-orchestration"],
    pillarLinks: [
      { name: "AI Execution School", href: "/ai-execution-school/" },
      { name: "Academic vs Applied AI", href: "/academic-ai-vs-applied-ai/" },
    ],
  },
  {
    slug: "academic-ai",
    term: "Academic AI",
    short: "The research-led path: studying ML theory, model architecture, and pure science.",
    body: "Academic AI is the research-focused path — math, theory, model architecture, optimisation, novel algorithms. Output: PhDs, research scientists, ML engineers at frontier labs. Best pursued at top academic universities (Indian or foreign). Distinct from applied AI, which uses existing models without re-training.",
    category: "Concepts",
    related: ["applied-ai", "fine-tuning", "training-data"],
    pillarLinks: [
      { name: "Academic vs Applied AI", href: "/academic-ai-vs-applied-ai/" },
    ],
  },
  {
    slug: "seo",
    term: "SEO",
    short: "Search Engine Optimisation — making pages findable on Google, Bing, AI Search.",
    body: "SEO (Search Engine Optimisation) is the practice of making web pages discoverable by search engines and AI search tools. In 2026, SEO has expanded to include AI-search-engine optimisation (ChatGPT Search, Perplexity, Claude, Bing Copilot) and traditional Google/Bing. Core levers: page quality, schema markup, internal linking, third-party citations, llms.txt files for AI agents.",
    category: "Concepts",
    related: ["ai-search", "ai-overviews"],
  },
  {
    slug: "google-ai-studio",
    term: "Google AI Studio",
    short: "Google's developer playground for testing Gemini and getting API keys.",
    body: "Google AI Studio (aistudio.google.com) is the free developer interface for Gemini. Test prompts, iterate on outputs, and generate API keys for production use. Generous free tier — most early-stage AI apps run entirely on the free quota.",
    category: "Tools",
    related: ["gemini", "openai", "api"],
  },
  {
    slug: "inference",
    term: "Inference",
    short: "The process of running a trained AI model to get a prediction or output.",
    body: "Inference is what happens when you call an LLM — the model is run to produce an output for your input. Distinct from training (where the model is being created). 'Inference cost' refers to the per-call cost of running the model. Companies like Groq specialise in fast inference.",
    category: "Concepts",
    related: ["llm", "groq", "tokens", "api"],
  },

  // ── 2026 expansion: 40 new entries targeting unranked head-terms in
  //    keyword bank (agentic-ai, mlops, ai-marketing, India model news,
  //    function-calling, structured output, eval, etc.). Each entry is
  //    100-200 words, internally cross-linked, and SEO-anchored to the
  //    most relevant pillar page or program.
  {
    slug: "agentic-ai",
    term: "Agentic AI",
    short: "AI systems that plan, decide, and act on multi-step goals with minimal human oversight.",
    body: "Agentic AI describes LLM-powered systems that go beyond single-turn chat — they plan a sequence of steps, call tools, observe results, and adapt. Unlike a one-shot prompt, an agent runs until a goal is met or a stop condition fires. Examples: a research agent that browses, summarises, and emails a brief; a sales agent that enriches leads and drafts follow-ups; a coding agent that opens a PR end-to-end. Agentic AI is the active frontier in 2026, and ONROL's AI Architect track is built around shipping production agents.",
    category: "Concepts",
    alsoKnownAs: ["AI agents", "Autonomous AI", "Agentic systems"],
    related: ["ai-agent", "ai-orchestration", "tool-use", "mcp", "function-calling"],
    pillarLinks: [{ name: "AI Architect program", href: "/programs/ai-architect/" }],
  },
  {
    slug: "function-calling",
    term: "Function Calling",
    short: "An LLM feature that lets the model invoke your code/APIs in a structured way.",
    body: "Function calling (or 'tool use' in Anthropic's vocabulary) is the mechanism by which an LLM decides to call your defined function — like get_weather(city) or send_email(to, body) — and returns a structured JSON payload of arguments instead of free text. You execute the function, return the result, and the model continues. It is the core primitive behind every modern AI agent, every voice assistant, and every workflow automation built on Claude, GPT, or Gemini. Function calling is what turns an LLM from a chatbot into something that can DO things.",
    category: "Concepts",
    alsoKnownAs: ["Tool use", "Tool calling", "Function invocation"],
    related: ["tool-use", "ai-agent", "structured-output", "mcp", "agentic-ai"],
    pillarLinks: [{ name: "AI Architect program", href: "/programs/ai-architect/" }],
  },
  {
    slug: "structured-output",
    term: "Structured Output",
    short: "Forcing an LLM to return JSON / typed data that matches a schema you define.",
    body: "Structured output is the technique of constraining an LLM to return data in a precise format — usually JSON conforming to a schema you specify. Without it, you get prose that needs parsing; with it, you get an object you can plug straight into your code. Modern LLMs (Claude, GPT-4o, Gemini) support structured output natively via response_format or tool-use schemas. It is essential for any production AI feature: classification, extraction, agent state machines, form filling, lead scoring.",
    category: "Concepts",
    alsoKnownAs: ["JSON mode", "Schema-constrained generation", "Typed output"],
    related: ["function-calling", "tool-use", "ai-agent", "prompt-engineering"],
  },
  {
    slug: "ai-eval",
    term: "AI Evaluation (Eval)",
    short: "The discipline of measuring whether an AI system is actually doing the job correctly.",
    body: "AI evaluation — usually shortened to 'evals' — is how you measure LLM output quality on a defined task. Evals can be deterministic (regex match, exact answer) or LLM-judged (one model grades another). Without evals you cannot tell whether a prompt change made things better or worse, whether a new model upgrade is safe to ship, or whether your agent is regressing in production. Frameworks like Anthropic Evals, OpenAI Evals, Promptfoo, and Inspect AI are standard in 2026.",
    category: "Concepts",
    alsoKnownAs: ["LLM eval", "Model evaluation", "AI testing"],
    related: ["llm", "fine-tuning", "ai-agent", "applied-ai"],
  },
  {
    slug: "prompt-injection",
    term: "Prompt Injection",
    short: "An attack where malicious input overrides the developer's intended LLM instructions.",
    body: "Prompt injection is the AI-era equivalent of SQL injection. An attacker embeds instructions inside data the LLM reads — a webpage, a PDF, an email, a tool result — that hijacks the model into doing something the developer never intended (exfiltrating data, calling unauthorised tools, bypassing safety rules). It is the #1 unsolved security risk in agentic AI. Defences include input sanitisation, system-prompt locking, sandboxed tool execution, and human-in-the-loop confirmation for sensitive actions.",
    category: "Concepts",
    alsoKnownAs: ["Indirect prompt injection", "Jailbreak"],
    related: ["ai-agent", "agentic-ai", "system-prompt", "tool-use"],
  },
  {
    slug: "mlops",
    term: "MLOps",
    short: "DevOps for machine learning — versioning, deploying, and monitoring AI models in production.",
    body: "MLOps (Machine Learning Operations) is the practice of running ML and AI systems in production reliably. It covers data pipelines, model versioning, experiment tracking, deployment, monitoring, and retraining. Tools: MLflow, Weights & Biases, BentoML, Kubeflow, NVIDIA AI Enterprise. In 2026, MLOps has bifurcated: classical-ML MLOps (still about training pipelines) and LLMOps (prompt management, eval pipelines, RAG observability). ONROL covers the LLMOps slice that matters for shipping AI products without an ML PhD.",
    category: "Concepts",
    alsoKnownAs: ["LLMOps", "AIOps", "ML Engineering"],
    related: ["ai-eval", "fine-tuning", "applied-ai", "ai-agent"],
  },
  {
    slug: "aiops",
    term: "AIOps",
    short: "Using AI to automate IT operations — incident detection, root-cause analysis, remediation.",
    body: "AIOps applies AI/ML to IT operations data (logs, metrics, traces) to detect anomalies, correlate incidents, and suggest or execute fixes. Distinct from MLOps (which is about running ML systems). In 2026, AIOps platforms increasingly use LLMs to summarise incidents and write postmortems automatically. Common tools: Datadog Watchdog, Dynatrace Davis AI, BigPanda, Moogsoft.",
    category: "Concepts",
    alsoKnownAs: ["Intelligent Operations", "AI for ITOps"],
    related: ["mlops", "automation", "ai-agent"],
  },
  {
    slug: "ai-engineer",
    term: "AI Engineer",
    short: "A new professional role: shipping AI products by composing models, prompts, tools, and APIs.",
    body: "The AI Engineer is the dominant new job created by the LLM era. Unlike an ML researcher (who trains models) or a data scientist (who analyses data), an AI engineer ships AI products — combining off-the-shelf foundation models with prompts, RAG, tools, evals, and orchestration to deliver real user value. Most ONROL graduates target this role because it requires no PhD, pays well in India and globally, and is the job most companies are actually hiring for in 2026.",
    category: "Career",
    alsoKnownAs: ["Applied AI Engineer", "LLM Engineer", "GenAI Engineer"],
    related: ["applied-ai", "mlops", "ai-orchestration", "ai-agent"],
    pillarLinks: [{ name: "AI Generalist program", href: "/programs/ai-generalist/" }],
  },
  {
    slug: "generative-ai",
    term: "Generative AI",
    short: "Umbrella term for AI that creates new content — text, code, images, audio, video.",
    body: "Generative AI (GenAI) covers any AI system that produces novel output: text (ChatGPT, Claude, Gemini), images (Midjourney, DALL·E, Stable Diffusion), audio (ElevenLabs, Suno), video (Sora, Veo, Runway), code (Copilot, Cursor). The category exploded in 2022-2026 and is now the dominant business AI category. Most enterprise 'AI strategy' in 2026 is, in practice, GenAI strategy.",
    category: "Concepts",
    alsoKnownAs: ["GenAI"],
    related: ["llm", "image-generation", "video-generation", "applied-ai"],
  },
  {
    slug: "image-generation",
    term: "Image Generation",
    short: "AI models that create images from text prompts — Midjourney, DALL·E, Stable Diffusion, Flux.",
    body: "Image generation models translate a text description into a synthesised image. The 2026 leaders are Midjourney v7 (best aesthetic), DALL·E 4 (inside ChatGPT), Stable Diffusion 4, and Flux (open weights). Used for marketing creatives, product mockups, storyboards, and personalised content. ONROL's marketing creator path covers prompting these models for brand-consistent output.",
    category: "Tools",
    alsoKnownAs: ["AI image", "Text-to-image", "Diffusion"],
    related: ["generative-ai", "video-generation", "ai-marketing"],
  },
  {
    slug: "video-generation",
    term: "Video Generation",
    short: "AI models that produce video from text or images — Sora, Veo, Runway, Pika.",
    body: "AI video generation moved from novelty to production-grade in 2026 with Sora 2 (OpenAI), Veo 3.1 (Google), Runway Gen-4, and Pika 2. Use cases: short-form social content, explainer reels, ad creative, dynamic product demos. Output is broadcast-grade in many cases. ONROL covers AI video as part of the AI-for-marketers track.",
    category: "Tools",
    alsoKnownAs: ["Text-to-video", "AI video"],
    related: ["generative-ai", "image-generation", "ai-marketing"],
  },
  {
    slug: "speech-to-text",
    term: "Speech-to-Text",
    short: "AI that transcribes spoken audio into written text — Whisper, AssemblyAI, Deepgram.",
    body: "Speech-to-text (STT, also called ASR — automatic speech recognition) converts spoken audio into written text. OpenAI Whisper (open-weight) is the dominant baseline; AssemblyAI, Deepgram, and Sarvam Saaras lead for commercial multilingual quality. Critical for meeting transcription, customer-call analytics, voice agents, and accessibility.",
    category: "Tools",
    alsoKnownAs: ["ASR", "Speech recognition", "Transcription"],
    related: ["whisper", "text-to-speech", "ai-agent"],
  },
  {
    slug: "whisper",
    term: "Whisper",
    short: "OpenAI's open-source speech-to-text model — the baseline for AI transcription in 2026.",
    body: "Whisper is OpenAI's open-source automatic speech recognition (ASR) model, released 2022 and refined through 2026. It transcribes 99 languages with near-human accuracy and runs locally on consumer hardware. Most paid transcription products either use Whisper directly or benchmark against it. Best free starting point for any voice-first AI project.",
    category: "Tools",
    related: ["speech-to-text", "openai", "ai-agent"],
  },
  {
    slug: "text-to-speech",
    term: "Text-to-Speech",
    short: "AI that turns text into natural-sounding spoken audio — ElevenLabs, OpenAI TTS, Sarvam.",
    body: "Text-to-speech (TTS) generates audio from text. ElevenLabs leads commercially for voice cloning and emotional range; OpenAI TTS-1 is a strong default for English; Sarvam TTS leads for Indic languages. Used in voice agents, audiobooks, podcasts, accessibility, IVR replacement, and short-form video voiceover.",
    category: "Tools",
    alsoKnownAs: ["TTS", "AI voice"],
    related: ["speech-to-text", "elevenlabs", "ai-agent"],
  },
  {
    slug: "elevenlabs",
    term: "ElevenLabs",
    short: "The leading AI voice / TTS platform — natural voices, voice cloning, multilingual support.",
    body: "ElevenLabs is the dominant commercial AI voice platform in 2026. It generates natural-sounding speech from text, clones voices from short samples, dubs videos across 30+ languages, and powers most production voice agents. Free tier sufficient for prototypes; pay-as-you-go for production volume. Covered in ONROL's voice-AI module.",
    category: "Tools",
    related: ["text-to-speech", "ai-agent", "voice-agent"],
  },
  {
    slug: "voice-agent",
    term: "Voice Agent",
    short: "An AI system you can talk to — combines speech-to-text, an LLM, tool use, and text-to-speech.",
    body: "A voice agent is the conversational layer over an LLM agent: STT (Whisper, Deepgram) feeds an LLM (Claude, GPT-4o), which calls tools and returns text routed through TTS (ElevenLabs) back to the caller. Used in inbound support, sales-qualification calls, appointment booking, and 24/7 reception. ONROL's AI Architect track ships a working voice agent on day 4.",
    category: "Concepts",
    alsoKnownAs: ["AI voice agent", "Conversational AI"],
    related: ["ai-agent", "speech-to-text", "text-to-speech", "elevenlabs", "function-calling"],
    pillarLinks: [{ name: "AI Architect program", href: "/programs/ai-architect/" }],
  },
  {
    slug: "ai-marketing",
    term: "AI Marketing",
    short: "Using AI tools to plan, create, target, and measure marketing — the dominant marketer skillset of 2026.",
    body: "AI marketing covers any application of AI to the marketing stack: ChatGPT/Claude for copy, Midjourney for creative, ElevenLabs for voice, Veo/Sora for video, AI agents for SEO research and outreach, predictive models for targeting. The 2026 baseline is no longer 'should marketers use AI' but 'how aggressively'. ONROL's AI-for-marketers track shows how to compress a 3-month campaign into one afternoon.",
    category: "Career",
    alsoKnownAs: ["AI digital marketing", "AI for marketers"],
    related: ["ai-seo", "ai-content-marketing", "image-generation", "video-generation"],
  },
  {
    slug: "ai-seo",
    term: "AI SEO",
    short: "Optimising for AI search engines and AI Overviews — the new layer above classical SEO.",
    body: "AI SEO is the discipline of getting cited inside AI answers — Google AI Overviews, ChatGPT search, Perplexity, Claude. Tactics include structured data (schema.org), entity-clear copy, citation-friendly formatting, and surface alignment with model training cuts. Distinct from classical Google ranking but increasingly the larger traffic source for high-intent queries in 2026.",
    category: "Career",
    alsoKnownAs: ["GEO", "Generative Engine Optimization", "AI search optimization"],
    related: ["ai-overviews", "ai-search", "seo", "ai-marketing"],
  },
  {
    slug: "ai-content-marketing",
    term: "AI Content Marketing",
    short: "Producing high-volume, brand-consistent content at scale using LLMs and structured workflows.",
    body: "AI content marketing pairs LLMs with brand voice guides, fact-check loops, and editorial review to publish at 10-100x the volume of a human-only team. Quality depends on prompt engineering, source-citing RAG pipelines, and disciplined human edit passes. The companies winning in 2026 treat AI as the writer's first draft engine, not the publisher.",
    category: "Career",
    related: ["ai-marketing", "ai-seo", "rag", "prompt-engineering"],
  },
  {
    slug: "ai-performance-marketing",
    term: "AI Performance Marketing",
    short: "Using AI to test, target, and optimise paid ad campaigns — Meta Advantage+, Google PMax, Smartly.",
    body: "AI performance marketing uses ML-driven bidding, audience targeting, and creative variation to maximise ROAS on paid platforms. Meta Advantage+, Google Performance Max, and Smartly.io are the dominant tools. In 2026 the marketer's role shifts from manual lever-pulling to creative strategy and signal quality (first-party data, conversion API, server-side tagging).",
    category: "Career",
    related: ["ai-marketing", "ai-seo", "automation"],
  },
  {
    slug: "no-code-ai",
    term: "No-Code AI",
    short: "Building AI products visually — without writing traditional code.",
    body: "No-code AI tools let non-engineers build production AI workflows. Categories: visual workflow builders (n8n, Make, Zapier), AI app builders (Bolt.new, Lovable, v0), agent platforms (CrewAI, Lindy, Stack AI), and front-end app generators (Replit Agent, Cursor Compose). ONROL's flagship is built around no-code AI because it is the fastest path from idea to deployed product for non-coders.",
    category: "Concepts",
    alsoKnownAs: ["No-code GenAI", "Visual AI"],
    related: ["vibe-coding", "n8n", "zapier", "bolt-new", "lovable", "automation"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "low-code-ai",
    term: "Low-Code AI",
    short: "Mostly-visual AI development with thin code escape hatches for power users.",
    body: "Low-code AI sits between no-code and full-code: a visual canvas for the 80% case, with the option to drop into JavaScript, Python, or SQL when you need precision. Examples: Retool, Bubble, Glide. Often the right choice for internal tools where pure no-code hits a wall but a full engineering hire is overkill.",
    category: "Concepts",
    related: ["no-code-ai", "vibe-coding", "automation"],
  },
  {
    slug: "india-ai-mission",
    term: "India AI Mission",
    short: "₹10,372 crore Indian government programme to build sovereign AI compute, datasets, and skills.",
    body: "The IndiaAI Mission, approved March 2024 by the Union Cabinet, is India's national AI strategy — funding sovereign GPU compute clusters (10,000+ GPUs), open Indic datasets (Bhashini), startup grants (IndiaAI Innovation Centre), and applied-AI skills under the FutureSkills Prime banner. The 2026 India AI Impact Summit in Delhi positioned India as a credible third pole in global AI policy and capacity.",
    category: "India",
    alsoKnownAs: ["IndiaAI", "IndiaAI Mission"],
    related: ["sarvam-ai", "krutrim-ai", "bhashini", "ai-policy-india"],
  },
  {
    slug: "sarvam-ai",
    term: "Sarvam AI",
    short: "Bengaluru-based Indic LLM lab — open-source 105B model, multilingual TTS/STT, India-first.",
    body: "Sarvam AI is the leading Indian LLM startup, founded by Vivek Raghavan and Pratyush Kumar (also of Bhashini and AI4Bharat). Their Sarvam-105B (released early 2026) is the largest open-source model trained primarily on Indian languages, with state-of-the-art Indic STT (Sarvam-1) and TTS quality. Backed by Lightspeed, Peak XV, and the IndiaAI Mission's compute allocation.",
    category: "India",
    related: ["india-ai-mission", "krutrim-ai", "bhashini", "llm"],
  },
  {
    slug: "krutrim-ai",
    term: "Krutrim AI",
    short: "Ola-founded Indian LLM and infra company — Bharat-2B model, sovereign cloud play.",
    body: "Krutrim was India's first AI unicorn (Jan 2024), founded by Bhavish Aggarwal alongside Ola. After early consumer-LLM ambitions, Krutrim pivoted in late 2025 to sovereign GPU cloud and Indic-LLM infrastructure, releasing the Bharat-2B open-weight model. Lessons from that pivot inform much of ONROL's coverage of Indian AI strategy.",
    category: "India",
    related: ["india-ai-mission", "sarvam-ai", "llm"],
  },
  {
    slug: "bhashini",
    term: "Bhashini",
    short: "India's national AI translation platform — bridging 22 official Indian languages.",
    body: "Bhashini is India's government-funded language-AI platform under the Digital India BHASHINI Mission. Provides ASR, TTS, MT, and OCR APIs across 22 scheduled Indian languages, free for developers. Powers government-services voice access and a growing ecosystem of Indic AI applications.",
    category: "India",
    related: ["india-ai-mission", "sarvam-ai", "speech-to-text", "text-to-speech"],
  },
  {
    slug: "ai-policy-india",
    term: "AI Policy (India)",
    short: "India's evolving AI regulation — the 2026 IndiaAI Governance Guidelines + DPDPA interplay.",
    body: "Indian AI policy in 2026 sits at the intersection of the Digital Personal Data Protection Act (DPDPA), the IndiaAI Governance Guidelines, and sector-specific norms (RBI for fintech AI, MoHFW for medical AI). India has so far rejected an EU-AI-Act-style horizontal framework in favour of risk-based, sectoral, mostly-voluntary guidance. Founders should track DPDPA enforcement notifications and MeitY advisories.",
    category: "India",
    related: ["india-ai-mission", "compliance"],
  },
  {
    slug: "claude-opus-4-7",
    term: "Claude Opus 4.7",
    short: "Anthropic's flagship 2026 reasoning + coding model — 1M-token context, top of the SWE-bench leaderboard.",
    body: "Claude Opus 4.7, released early 2026 by Anthropic, is the largest and most capable Claude variant. State-of-the-art on SWE-bench (real-world coding), strong on agentic-tool-use benchmarks, and the first model to ship 1M-token context as standard. The default 'serious work' model for ONROL's Architect track.",
    category: "Models",
    alsoKnownAs: ["Opus 4.7"],
    related: ["claude", "anthropic", "context-window", "ai-agent"],
  },
  {
    slug: "claude-sonnet-4-6",
    term: "Claude Sonnet 4.6",
    short: "The mid-tier 2026 Claude model — fast, cheap, very capable on most production tasks.",
    body: "Claude Sonnet 4.6 is the workhorse of Anthropic's 2026 lineup: ~5x cheaper than Opus 4.7 with ~80% of the capability on most real-world tasks. Default model for production AI features where cost and latency matter, and the model ONROL teaches first because every learner can afford to experiment with it.",
    category: "Models",
    alsoKnownAs: ["Sonnet 4.6"],
    related: ["claude", "claude-opus-4-7", "anthropic", "inference"],
  },
  {
    slug: "gpt-5-5",
    term: "GPT-5.5",
    short: "OpenAI's late-2026 flagship — multimodal reasoning, persistent memory, native agent loop.",
    body: "GPT-5.5 is OpenAI's flagship 2026 model — successor to GPT-5 with persistent cross-session memory, native multimodal reasoning (image, audio, video in/out), and a built-in agent loop. Powers ChatGPT and the OpenAI API. Strong rival to Claude Opus 4.7 across most leaderboards.",
    category: "Models",
    related: ["chatgpt", "openai", "gemini", "agentic-ai"],
  },
  {
    slug: "gemini-3",
    term: "Gemini 3",
    short: "Google's 2026 flagship — 2M-token context, deep Workspace integration, strong on multimodal.",
    body: "Gemini 3 (and the 3 Pro variant) is Google DeepMind's flagship 2026 model. Headline features: 2M-token context, leading multimodal video understanding, and direct embedding inside Google Workspace + Android. Powers Gemini.google.com and the Gemini API.",
    category: "Models",
    related: ["gemini", "google-deepmind", "context-window"],
  },
  {
    slug: "deepseek-v4",
    term: "DeepSeek V4",
    short: "Chinese open-weight LLM — very strong reasoning at a fraction of Opus pricing.",
    body: "DeepSeek V4, released early 2026, is the latest in the DeepSeek line of open-weight Chinese-developed LLMs. Notable for matching the reasoning quality of Claude Opus 4.7 on math and coding benchmarks at roughly 1/10 the API cost. Widely deployed for cost-sensitive workloads in India and globally.",
    category: "Models",
    related: ["llm", "claude-opus-4-7", "open-weights"],
  },
  {
    slug: "mistral-small-4",
    term: "Mistral Small 4",
    short: "Compact European open-weight model — strong on European languages, runs on a single GPU.",
    body: "Mistral Small 4 (2026) is the compact tier of Mistral AI's open-weight family. Runs on a single consumer-grade GPU, strong multilingual performance (especially French, German, Italian, Spanish), and a permissive Apache 2.0 licence. Default choice for self-hosted European AI workloads.",
    category: "Models",
    related: ["llm", "open-weights", "fine-tuning"],
  },
  {
    slug: "open-weights",
    term: "Open-Weights Model",
    short: "An LLM whose trained parameters are publicly downloadable — Llama, Mistral, DeepSeek, Sarvam.",
    body: "An open-weights model is one whose trained parameter weights are publicly downloadable — letting you run it on your own hardware, fine-tune it, and deploy it without per-token vendor fees. Distinct from 'open-source' (which would also include training data and code, rare in practice). Leading 2026 open-weights families: Llama (Meta), Mistral, DeepSeek, Qwen, Sarvam.",
    category: "Concepts",
    alsoKnownAs: ["Open weights", "Open-source LLM"],
    related: ["llm", "fine-tuning", "deepseek-v4", "mistral-small-4", "sarvam-ai"],
  },
  {
    slug: "vibe-coding-tools",
    term: "Vibe Coding Tools",
    short: "AI-first IDEs and app builders that turn plain-English prompts into working software.",
    body: "Vibe coding tools generate, edit, and deploy production code from natural-language prompts. The 2026 leaders: Cursor (best for engineers), Bolt.new + Lovable (best for non-coders), v0 (best for design-first React UIs), Replit Agent (best for full-stack with hosting), Windsurf (Cascade agent loop). ONROL's AI Generalist programme ships a deployed website built entirely in vibe-coding tools on day 2.",
    category: "Tools",
    related: ["vibe-coding", "cursor", "bolt-new", "lovable", "v0", "replit"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "windsurf",
    term: "Windsurf",
    short: "AI-native IDE from Codeium — Cascade agent that reasons over your whole repo.",
    body: "Windsurf is Codeium's AI-first IDE, distinguished by the 'Cascade' agent that plans across your full repository, edits multiple files in one turn, and runs tests in a loop until green. A direct competitor to Cursor, with strong free-tier limits and an aggressive 2026 push into the Indian developer market.",
    category: "Tools",
    related: ["cursor", "vibe-coding", "vibe-coding-tools", "github-copilot"],
  },
  {
    slug: "ai-jobs-india",
    term: "AI Jobs (India)",
    short: "The fastest-growing job category in India 2026 — AI engineers, prompt engineers, AI marketers.",
    body: "AI jobs in India spiked through 2025-26 as enterprises went from pilot to production. The biggest hiring surfaces: AI engineer (₹15-60L), prompt engineer / AI specialist (₹8-30L), AI product manager (₹25-60L), AI marketer / content lead (₹10-40L), AI sales engineer (₹20-50L). ONROL's outcomes track is built around these roles.",
    category: "Career",
    related: ["ai-engineer", "applied-ai", "ai-marketing"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "ai-bootcamp",
    term: "AI Bootcamp",
    short: "Intensive short-format AI programmes — 3 months to 12 weeks — for working professionals.",
    body: "An AI bootcamp is a short, intensive AI training format aimed at adults already in work — distinct from a college degree or a 6-month course. The Indian market in 2026 is dominated by 3-month to 12-week programmes covering prompt engineering, AI tools, automation, and (in the better ones) shipped projects. ONROL's flagship is a 3-month execution-first bootcamp.",
    category: "Career",
    alsoKnownAs: ["AI training programme", "AI intensive"],
    related: ["ai-engineer", "ai-jobs-india", "applied-ai"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "ai-course-online",
    term: "AI Course (Online)",
    short: "Self-paced or live online AI training — quality varies wildly; outcomes depend on shipping.",
    body: "Online AI courses range from free YouTube playlists to ₹1-5L paid programmes. The deciding factor for outcomes is not duration or price — it is whether the learner ships real projects. ONROL's online AI course (the AI Generalist programme) is built around three deployed projects in 3 months, not a video library.",
    category: "Career",
    alsoKnownAs: ["Online AI training", "AI online programme"],
    related: ["ai-bootcamp", "ai-engineer", "applied-ai"],
    pillarLinks: PILLAR_BEGINNERS,
  },
  {
    slug: "ai-portfolio",
    term: "AI Portfolio",
    short: "A public collection of shipped AI projects — the modern resume for AI roles.",
    body: "An AI portfolio is the proof-of-work artefact every aspiring AI engineer needs in 2026. Three or four deployed projects (a working web app, an automation that runs daily, a fine-tuned model, a Hugging Face Space) outperform any certificate in hiring conversations. ONROL ships every learner with three portfolio-grade projects.",
    category: "Career",
    related: ["ai-engineer", "ai-jobs-india", "ai-bootcamp"],
    pillarLinks: PILLAR_BEGINNERS,
  },
];

// Hand back the categories list for the index-page filter UI.
export function glossaryCategories(): string[] {
  const set = new Set<string>();
  for (const e of glossary) set.add(e.category);
  return ["All", ...Array.from(set)];
}
