export const homeData = {
  hero: {
    badge: "India's AI Execution School",
    headline: "Stop learning AI. Start earning from it.",
    supportHeadline: "",
    subheadline: "",
    supportCopy: "",
    primaryCta: { label: "Reserve Your Seat", href: "#contact" },
    secondaryCta: { label: "Download Brochure", href: "#brochure" },
    tertiaryCta: { label: "Explore Programs", href: "#programs" },
    chips: [],
    popupChip: "Limited seats — apply now",
    // Stats removed from hero strip per request — kept as empty array so
    // any component that maps over it renders nothing.
    stats: [],
  },
  intro: {
    title: "What is ONROL?",
    body:
      "ONROL was built for people overwhelmed by AI hype but unclear on how to turn it into something useful, deployable, and monetizable. It is not another passive content bootcamp.",
    points: [
      "Transforms passive AI consumers into confident AI builders",
      "Focused on real products, not endless tutorials",
      "Built for action, not theory",
      "Designed to bridge learning and income",
    ],
    quote: "We are not another tech bootcamp. We teach you what to do with AI.",
  },
  offerings: {
    title: "What do we do?",
    body:
      "We eliminate the distance between testing AI tools and earning real income from them. Through intensive 3-month bootcamps and advanced tracks, learners build real outputs with direct guidance from top practitioners.",
    cards: [
      { title: "Custom AI Assistants", description: "Build assistants tailored to real business and personal workflows." },
      { title: "Automated Business Workflows", description: "Connect tools, APIs, and AI models into execution systems." },
      { title: "Live Production-Ready Websites", description: "Launch real sites with AI-assisted development and deployment." },
    ],
    cta: { label: "See Our Programs", href: "#programs" },
  },
  why: {
    title: "Why do we do it?",
    body:
      "The AI hype cycle is crowded with experiments but very little execution. Millions try AI tools, but very few know how to turn those experiments into impact, opportunity, or income.",
    quote: "AI won't replace you, but someone using AI will.",
    points: [
      "Startups need custom internal systems",
      "Agencies need intelligent workflows",
      "Businesses need automation architects",
    ],
    close: "ONROL gives learners the roadmap, mentorship, and confidence to seize those opportunities.",
  },
  video: {
    title: "See what building with ONROL actually looks like",
    description: "Watch how learners move from tools to real execution.",
    formTitle: "Quick Apply — start your AI building journey",
    formSubtitle: "30 seconds. A team member reaches out the same day.",
    primaryCta: { label: "Register Now", href: "#contact" },
    secondaryCta: { label: "Download Brochure", href: "#brochure" },
  },
  personas: {
    title: "Which best describes you?",
    description: "Your starting point matters. Pick the closest fit — we'll tailor the path.",
    items: [
      {
        id: "student",
        emoji: "🎓",
        title: "I'm a student",
        blurb: "Get ahead of your peers with a portfolio of shipped AI projects before graduation.",
        outcomes: ["Build 3 real projects in 3 months", "Land internships faster", "ONROL Community peer network"],
        cta: { label: "See student path", href: "#contact" },
      },
      {
        id: "professional",
        emoji: "💼",
        title: "I'm a working professional",
        blurb: "Automate the repetitive work that's eating your week and become indispensable at work.",
        outcomes: ["Automate your workflow stack", "Lead AI initiatives at work", "Weekend-friendly cohorts"],
        cta: { label: "See professional path", href: "#contact" },
      },
      {
        id: "founder",
        emoji: "🚀",
        title: "I'm a founder or freelancer",
        blurb: "Ship AI products and agency offers without hiring a technical team.",
        outcomes: ["Launch AI offers / MVPs", "Productize your expertise", "Client-ready deliverables"],
        cta: { label: "See founder path", href: "#contact" },
      },
    ],
  },
  apex: {
    badge: "ONROL Community",
    title: "What happens inside ONROL Community",
    description: "ONROL Community is our private community of ONROL alumni, mentors, and active practitioners. 1 year of access comes with every program.",
    pillars: [
      { title: "Weekly build sessions", body: "Live working sessions where you ship alongside mentors and peers." },
      { title: "Freelance & project board", body: "Real client briefs and collaboration matches posted by the community." },
      { title: "Mentor office hours", body: "Drop-in Q&A with practitioners for unstick, reviews, and career guidance." },
      { title: "Alumni network", body: "Warm intros to past learners hiring, building, and collaborating." },
    ],
    cta: { label: "Join ONROL Community", href: "task" },
  },
  programsPreview: {
    title: "Programs built for real execution",
    cards: [
      {
        title: "AI Generalist Program",
        subtitle: "AI User → AI Builder · 3-Month Live Cohort",
        description: "The fastest path from passive AI consumption to deployed AI products. Built for non-coders, working professionals, and freelancers.",
        duration: "3 Months",
        tag: "Beginner-friendly",
        outputs: ["Backend automation system", "Vibe-coded live website", "Personal AI assistant"],
        cta: { label: "Explore Generalist", href: "/programs/ai-generalist" },
      },
      {
        title: "AI Architect Program",
        subtitle: "AI Builder → AI Architect · 6-Month Mastery",
        description: "Design, build, deploy and scale complete AI systems end-to-end — agents, products, architecture. For those going beyond using tools.",
        duration: "6 Months",
        tag: "Advanced",
        outputs: ["Full-stack AI products & agents", "Production system architecture", "Capstone + AI Architect Certification"],
        cta: { label: "Explore Architect", href: "/programs/ai-architect" },
      },
    ],
  },
  comparison: {
    title: "The ONROL Difference: Why Learn With Us?",
    callout: "We build architects, not academics.",
    rows: [
      { label: "Duration", onrol: "3-month intensive + advanced growth path", typical: "Long theory-first timeline" },
      { label: "Community", onrol: "1 year ONROL Community access", typical: "Basic community access" },
      { label: "Mentors", onrol: "Active practitioners from top teams", typical: "General instructors" },
      { label: "Prerequisites", onrol: "No heavy coding prerequisites", typical: "Often technical barriers" },
      { label: "Final Output", onrol: "3 live projects and portfolio proof", typical: "Completion certificate only" },
      { label: "Delivery Format", onrol: "Immersive workshop execution model", typical: "Content-heavy classroom model" },
      { label: "End Goal", onrol: "Multiple monetization pathways", typical: "Knowledge without execution support" },
    ],
  },
  toolCategories: ["All", "LLMs", "Automation", "Agents", "Coding", "Research", "Design", "Video", "Audio", "Productivity", "Infra"],
  tools: [
    { name: "ChatGPT", category: "LLMs" },
    { name: "Claude", category: "LLMs" },
    { name: "Gemini", category: "LLMs" },
    { name: "Perplexity", category: "Research" },
    { name: "Mistral", category: "LLMs" },
    { name: "Llama", category: "LLMs" },
    { name: "Cohere Command", category: "LLMs" },
    { name: "Groq", category: "LLMs" },
    { name: "DeepSeek", category: "LLMs" },
    { name: "Qwen", category: "LLMs" },
    { name: "Pi", category: "LLMs" },
    { name: "You.com", category: "Research" },
    { name: "Kagi", category: "Research" },
    { name: "Glean", category: "Research" },
    { name: "Elicit", category: "Research" },
    { name: "Consensus", category: "Research" },
    { name: "Scite", category: "Research" },
    { name: "Notion AI", category: "Productivity" },
    { name: "Coda AI", category: "Productivity" },
    { name: "Airtable AI", category: "Productivity" },
    { name: "ClickUp AI", category: "Productivity" },
    { name: "Asana AI", category: "Productivity" },
    { name: "Monday AI", category: "Productivity" },
    { name: "n8n", category: "Automation" },
    { name: "Zapier", category: "Automation" },
    { name: "Make", category: "Automation" },
    { name: "Pipedream", category: "Automation" },
    { name: "Bardeen", category: "Automation" },
    { name: "IFTTT", category: "Automation" },
    { name: "Relay", category: "Automation" },
    { name: "Workato", category: "Automation" },
    { name: "Tray.io", category: "Automation" },
    { name: "UiPath", category: "Automation" },
    { name: "LangChain", category: "Agents" },
    { name: "LlamaIndex", category: "Agents" },
    { name: "CrewAI", category: "Agents" },
    { name: "AutoGen", category: "Agents" },
    { name: "Haystack", category: "Agents" },
    { name: "DSPy", category: "Agents" },
    { name: "Semantic Kernel", category: "Agents" },
    { name: "OpenRouter", category: "Agents" },
    { name: "Flowise", category: "Agents" },
    { name: "Langflow", category: "Agents" },
    { name: "Cursor", category: "Coding" },
    { name: "GitHub Copilot", category: "Coding" },
    { name: "Codeium", category: "Coding" },
    { name: "Tabnine", category: "Coding" },
    { name: "Amazon Q Developer", category: "Coding" },
    { name: "Sourcegraph Cody", category: "Coding" },
    { name: "Replit", category: "Coding" },
    { name: "v0", category: "Coding" },
    { name: "Bolt", category: "Coding" },
    { name: "Loveable", category: "Coding" },
    { name: "Windsurf", category: "Coding" },
    { name: "Continue", category: "Coding" },
    { name: "Aider", category: "Coding" },
    { name: "Figma AI", category: "Design" },
    { name: "Canva AI", category: "Design" },
    { name: "Midjourney", category: "Design" },
    { name: "Leonardo AI", category: "Design" },
    { name: "Ideogram", category: "Design" },
    { name: "Adobe Firefly", category: "Design" },
    { name: "DALL-E", category: "Design" },
    { name: "Stable Diffusion", category: "Design" },
    { name: "Krea", category: "Design" },
    { name: "Magnific", category: "Design" },
    { name: "Framer AI", category: "Design" },
    { name: "Uizard", category: "Design" },
    { name: "Runway", category: "Video" },
    { name: "Pika", category: "Video" },
    { name: "Luma Dream Machine", category: "Video" },
    { name: "Synthesia", category: "Video" },
    { name: "HeyGen", category: "Video" },
    { name: "Descript", category: "Video" },
    { name: "CapCut AI", category: "Video" },
    { name: "VEED AI", category: "Video" },
    { name: "Veed", category: "Video" },
    { name: "InVideo AI", category: "Video" },
    { name: "ElevenLabs", category: "Audio" },
    { name: "PlayHT", category: "Audio" },
    { name: "Murf", category: "Audio" },
    { name: "Resemble AI", category: "Audio" },
    { name: "Suno", category: "Audio" },
    { name: "Udio", category: "Audio" },
    { name: "Auphonic", category: "Audio" },
    { name: "Cleanvoice", category: "Audio" },
    { name: "Whisper", category: "Audio" },
    { name: "AssemblyAI", category: "Audio" },
    { name: "Pinecone", category: "Infra" },
    { name: "Weaviate", category: "Infra" },
    { name: "Qdrant", category: "Infra" },
    { name: "Milvus", category: "Infra" },
    { name: "Chroma", category: "Infra" },
    { name: "Supabase", category: "Infra" },
    { name: "Vercel AI SDK", category: "Infra" },
    { name: "Modal", category: "Infra" },
    { name: "Replicate", category: "Infra" },
    { name: "Hugging Face Inference", category: "Infra" },
    { name: "Databricks Mosaic AI", category: "Infra" },
    { name: "Snowflake Cortex", category: "Infra" },
    { name: "Vertex AI", category: "Infra" },
    { name: "Azure AI Studio", category: "Infra" },
    { name: "Amazon Bedrock", category: "Infra" },
    { name: "LangSmith", category: "Infra" },
    { name: "PromptLayer", category: "Infra" },
    { name: "Helicone", category: "Infra" },
    { name: "Weights & Biases", category: "Infra" },
    { name: "Arize Phoenix", category: "Infra" },
  ],
  companies: [
    "OpenAI",
    "Google DeepMind",
    "Anthropic",
    "Meta AI",
    "Microsoft AI",
    "NVIDIA",
    "Hugging Face",
    "Perplexity",
    "Stability AI",
    "Mistral AI",
    "Cohere",
    "Runway",
    "ElevenLabs",
    "Databricks",
    "Scale AI",
    "Notion",
    "Canva",
    "Adobe",
    "Figma",
    "Zapier",
  ],
  mentors: [
    {
      name: "Meenakshi Kumari Jha",
      role: "Lead AI/ML Engineer · Lead Data Scientist",
      company: "AI & GenAI Solutions Architect",
      years: "6+ years experience",
      specializes:
        "Generative AI, Multi-Agent Systems, RAG, LLM Orchestration, Machine Learning, NLP, and Enterprise AI Platforms.",
      line:
        "Helps learners understand how real-world AI systems, RAG platforms, and multi-agent applications are designed and deployed.",
      tags: ["GenAI", "RAG", "LLM Orchestration"],
      photo: "/team/meenakshi-kumari-jha.jpg",
      bio: [
        "Meenakshi Kumari Jha is an AI and GenAI Solutions Architect with 6+ years of experience in enterprise AI systems, multi-agent architectures, RAG-based platforms, LLM orchestration, and scalable AI solution design.",
        "She has strong expertise in Generative AI, Machine Learning, NLP, Data Engineering, Cloud AI Deployments, Conversational AI, AI Observability, OpenSearch Optimization, FastAPI Microservices, and AWS Cloud Solutions.",
        "Her technology stack includes LangChain, LangGraph, CrewAI, OpenAI GPT models, Claude, Llama, Mistral, FastAPI, OpenSearch, Redis, PostgreSQL, Kubernetes, Docker, AWS, Python, SQL, MLflow, Langfuse, Kafka, Spark, Databricks, Tableau, and Power BI.",
        "She is Microsoft Certified in Business Intelligence, Artificial Intelligence, and Data Engineering. She has designed and implemented enterprise-scale GenAI systems with RAG architectures, observability pipelines, and production-grade AI deployments. She has also trained learners through Emarticus, Board Infinity, and Great Learning with consistent 4.5+ star ratings.",
      ],
    },
    {
      name: "Sridevi Edupuganti",
      role: "AI Generalist · AI Automation Specialist · Cloud & AI Architect",
      company: "Co-Founder — AI Automation & Workflows, ZenithWorks.AI",
      years: "25+ years experience",
      specializes:
        "AI Agents, n8n Automations, RAG Pipelines, Prompt Engineering, Cloud AI, Vibe Coding, and AI Monetization.",
      line:
        "Helps learners build practical AI automations, agents, workflows, and real-world AI productivity systems.",
      tags: ["AI Agents", "n8n", "Cloud AI"],
      photo: "/team/sridevi-edupuganti.jpg",
      bio: [
        "Sridevi Edupuganti is an AI Generalist, AI Automation Specialist, Cloud & AI Architect, Google Certified Prompt Engineer, n8n Verified Creator, 5× Azure Certified professional, and former Microsoft leader with 25+ years of experience.",
        "She is the Co-Founder of ZenithWorks.AI and actively mentors professionals and students through WE Hub, Outskill, ISB Executive Education, Outreach Network, Career Dwar, and Entrepreneurology Network.",
        "Her core expertise spans AI Agents, RAG Pipelines, n8n Workflow Automations, Generative AI, LLMs, Prompt Engineering, Context Engineering, AI Chatbots, Voice Assistants, Diffusion Models, Vibe Coding, Web Apps, Websites, Azure & AWS Cloud Architecture, AI-powered Data Analysis, Machine Learning, Deep Learning, Delivery Excellence, GTM Strategy, and Mentoring.",
        "She works with ChatGPT, Gemini, Claude, Perplexity, n8n, Azure AI, AWS, Diffusion Models, AI Clones, Voice Assistants, Chatbots, Python for Data Science, TensorFlow, NLP, Speech Recognition, and 30+ AI tools.",
        "She is a Guinness World Record holder, Mastercard AI in Business Excellence Award winner, FlyHigh Women Special Award recipient, and rated among the Top 5% of Mentors on Topmate with a 5/5 rating. She has mentored 4,000+ professionals and students.",
      ],
    },
    {
      name: "B V Ajithesh Gupta",
      role: "Senior Software Engineer",
      company: "Microsoft",
      years: "12+ years experience",
      specializes:
        "AI-assisted Coding, GitHub Copilot, Cursor AI, Azure OpenAI, GPT-based Solutions, and MCP-based Custom Skills.",
      line:
        "Helps learners understand how AI coding tools and GPT-based systems are used in modern software development.",
      tags: ["GitHub Copilot", "Cursor AI", "Azure OpenAI"],
      photo: "/team/ajithesh-gupta.jpg",
      bio: [
        "B V Ajithesh Gupta is a Senior Software Engineer at Microsoft with 12+ years of professional experience and 6+ years of training and teaching experience.",
        "His areas of expertise include software engineering, AI-assisted development, GitHub Copilot, Cursor AI, Azure OpenAI, GPT-based solutions, MCP-based custom skills development, and Copilot-based workflows.",
        "He brings practical industry exposure to how modern developers use AI coding assistants, Azure OpenAI, GPT-based systems, and custom AI skills to improve development speed, productivity, and implementation quality.",
        "Students will learn how AI is changing software development, how to work with AI coding tools effectively, and how GPT-based solutions are applied in enterprise software environments.",
      ],
    },
    {
      name: "Priteesh Joshi",
      role: "Certified Applied AI Implementation Lead · Corporate Trainer",
      company: "Applied AI Implementation & Corporate Training",
      years: "10+ years experience",
      specializes:
        "Generative AI, Agentic AI, AI-driven Automation, No-code App Development, AI Deployment, and AI Observability.",
      line:
        "Helps professionals and students implement real-world AI automation and deployment workflows.",
      tags: ["Agentic AI", "No-code", "AIOps"],
      photo: "/team/priteesh-joshi.jpg",
      bio: [
        "Priteesh Joshi is a Certified Applied AI Implementation Lead and Corporate Trainer with 10+ years of experience, focused on helping professionals and students implement AI automation and deployment workflows.",
        "He is an expert in Generative AI, agentic AI workflows, no-code app development, and AI observability, with an emphasis on actionable skills for building real-world AI systems.",
        "His specializations include Generative AI & Agentic AI, AI-driven automation, workflows and observability, no-code app development, AI deployment, AIOps, optimization, and operational AI.",
        "He brings 10+ years of corporate training experience and has delivered hands-on sessions on GenAI and automation tools.",
      ],
    },
    {
      name: "Pranay Devidas Pawar",
      role: "Associate Director of Operations",
      company: "HumanPowered Health Technologies",
      years: "19+ years experience",
      specializes:
        "US Healthcare Operations, RPA & GenAI in Healthcare, LMS Governance, Instructional Design, and Lean / Six Sigma.",
      line:
        "Operations leader driving performance, compliance, and automation transformation in US Healthcare.",
      tags: ["RPA", "Healthcare AI", "Six Sigma"],
      photo: "/team/pranay-devidas-pawar.jpg",
      bio: [
        "Pranay Devidas Pawar is Associate Director of Operations at HumanPowered Health Technologies with 19+ years of experience in US Healthcare, driving performance, compliance, and automation transformation.",
        "He specializes in US Healthcare operations, strategic leadership, training, process excellence, and automation integration.",
        "His tools and expertise span RPA & GenAI applications in healthcare operations, LMS governance, instructional design, eLearning authoring, analytics dashboards, and Lean / Six Sigma workflow optimization.",
        "He built RCM Academy (reducing onboarding by 25%), directed global training portfolios for 200+ FTE, and served as SME for training, quality audits, and ILT-to-eLearning conversion. He holds an MBA in International Leadership & Entrepreneurship and a Six Sigma Green Belt, and has scaled operations across 3 global locations delivering millions in efficiency gains.",
      ],
    },
    {
      name: "Sakshi Bhagchandani Pawar",
      role: "Associate Director — Automation, Analytics & AI",
      company: "Optum",
      years: "19+ years experience",
      specializes:
        "Azure AI, Agentic AI Frameworks, GenAI-driven Automation, Microsoft Copilot (M365), Power BI, and Process Intelligence.",
      line:
        "Leader in agentic AI, automation, and analytics transformation enabling data-driven scale.",
      tags: ["Azure AI", "Power BI", "Agentic AI"],
      photo: "/team/sakshi-bhagchandani-pawar.jpg",
      bio: [
        "Sakshi Bhagchandani Pawar is an Associate Director (Automation, Analytics & AI) at Optum with 19+ years of experience leading agentic AI, automation, and analytics transformation that enables data-driven scale.",
        "She specializes in enterprise AI automation, intelligent workflow orchestration, healthcare operations, program & portfolio management, and analytics-driven decision making.",
        "Her tools and expertise include Azure AI, agentic AI frameworks, GenAI-driven automation, Microsoft Copilot (M365), Power BI, Python for automation, task mining, process intelligence, and generative AI in healthcare.",
        "She has conducted workshops on AI adoption, Power BI, and SOP governance, and has mentored teams integrating AI, agentic workflows, and analytics into operational processes.",
      ],
    },
    {
      name: "Rahul Varma",
      role: "Pharma IT & CSV/CSA Expert",
      company: "Pharma IT · CSV / CSA / GxP Compliance",
      years: "13+ years experience",
      specializes:
        "Computer System Validation (CSV), Computer Software Assurance (CSA), GxP Compliance, Audit Readiness, and Pharma IT.",
      line:
        "Pharma IT specialist bridging industry expectations and real-world compliance skills.",
      tags: ["CSV", "CSA", "GxP"],
      photo: "/team/rahul-varma.jpg",
      bio: [
        "Rahul Varma is a Pharma IT and CSV/CSA expert with 13+ years of experience, bridging industry expectations and real-world compliance skills.",
        "He has worked with UHG (Optum), Aurobindo Pharma, and HCLTech supporting LEO Pharma, specializing in CSV, CSA, GxP compliance, quality systems, and audit readiness.",
        "His expertise spans Computer System Validation (CSV) and Computer Software Assurance (CSA), GxP compliance, audit readiness, Pharma IT processes, and training programs, hackathons, and awareness sessions for colleges and startups.",
        "He delivers end-to-end CSV/CSA training for freshers and professionals, publishes daily LinkedIn content simplifying CSV concepts into practical insights, and provides audit readiness and gap assessment support for organizations.",
      ],
    },
  ],
  community: {
    title: "Learning does not end after the session",
    cards: [
      { title: "Learn", description: "Structured learning paths with practitioner guidance." },
      { title: "Build", description: "Project sprints, showcase support, and output accountability." },
      { title: "Collaborate / Monetize", description: "ONROL Community collaboration, freelancing, agency, and startup opportunities." },
    ],
    ctas: [
      { label: "Join the ONROL Community", href: "task" },
      { label: "Register Now", href: "#contact" },
    ],
  },
  collaborations: {
    title: "Collaboration and ecosystem partnerships",
    body:
      "We work with colleges, communities, partners, and ecosystem allies to create high-impact workshops, learning events, and execution pathways.",
    ctas: [
      { label: "Partner with ONROL", href: "#contact" },
      { label: "Explore Community", href: "task" },
    ],
  },
  testimonials: {
    title: "What learners say after they start building",
    // Illustrative AI-generated placeholder portraits pending real cohort permissions.
    // Replace each item's `photo` and `name` once we have signed-off learner profiles.
    items: [
      {
        name: "Sandeep Kulkarni",
        background: "B.Tech student · Nagpur",
        quote:
          "Before ONROL I had a folder of saved tutorials and zero shipped projects. By the end I had three live URLs I could send recruiters.",
        photo: "/media/testimonials/aarav-sharma.jpg",
      },
      {
        name: "Fatima Sheikh",
        background: "Marketing manager · Lucknow",
        quote:
          "I went from 'AI is interesting' to running a Make.com automation that handles half my reporting. I got the time back inside a week.",
        photo: "/media/testimonials/priya-iyer.jpg",
      },
      {
        name: "Joel Mathew",
        background: "Freelance designer · Kochi",
        quote:
          "ONROL helped me package my skills into AI automation offers. Two new retainer clients in the month after the cohort.",
        photo: "/media/testimonials/rohan-mehta.jpg",
      },
    ],
  },
  interviews: {
    title: "Watch past learners walk through what they built",
    items: [
      { title: "From learner to builder", description: "How execution changed one learner's trajectory." },
      { title: "Mentor conversation: systems thinking", description: "What separates tool usage from orchestration capability." },
      { title: "Founder talk: AI execution in business", description: "Where real AI opportunities are emerging for builders." },
    ],
    ctas: [
      { label: "Watch more stories", href: "#interviews" },
      { label: "Register Now", href: "#contact" },
    ],
  },
  brochure: {
    title: "Program brochure",
    body:
      "Download the brochure to explore our programs, outcomes, mentoring model, learning paths, and execution ecosystem.",
    note: "Programs, outcomes, and dates may evolve with each cohort.",
    ctas: [
      { label: "Download Brochure", href: "#brochure" },
      { label: "Register Now", href: "#contact" },
    ],
  },
  contact: {
    title: "Let's help you choose the right path",
    subtitle: "Tell us where you are right now, and our team will guide you to the most relevant ONROL starting point.",
    interestOptions: [
      "AI Generalist Program",
      "Free Live Session",
      "Collaboration",
      "Community",
      "Other",
    ],
    ctas: [
      { label: "Submit Inquiry", href: "#contact" },
      { label: "Register Now", href: "#contact" },
    ],
  },
  finalCta: {
    title: "Your next AI project can start this week",
    subtitle: "Limited seats per cohort. Apply in 30 seconds and our team will guide your next step.",
    chips: ["Ship 3 real projects", "1-year ONROL Community access", "5 working days from zero to launched"],
    ctas: [
      { label: "Book a 15-min call", href: "#contact" },
      { label: "Download Brochure", href: "#brochure" },
    ],
  },
  footer: {
    brand: "ONROL",
    tagline: "India's AI Execution School",
    description:
      "Hyderabad-based premium AI education ecosystem focused on execution, outcomes, and monetization pathways.",
    contact: {
      email: "info@onrol.in",
      phone: "+91 99665 77659",
      website: "https://onrol.in",
      location: "Hyderabad, Telangana, India",
    },
    social: {
      linkedin: "https://in.linkedin.com/company/onrol",
      instagram: "https://www.instagram.com/onrol.in/",
      youtube: "https://www.youtube.com/@onrolofficial",
      whatsapp: "https://wa.me/919966577659?text=Hi%2C%20I%20want%20to%20know%20more%20about%20this%20program",
    },
  },
} as const;

export type HomeData = typeof homeData;
